name: resource_manager
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.1.0

  # Firebase
  firebase: ^9.0.2
  firebase_core: ^1.15.0
  firebase_storage: ^10.2.14
  cloud_firestore: ^3.1.13
  firebase_auth: ^3.3.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  change_app_package_name: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

